### ISSUE TITLE
FM support: cannot create single child relations

### ISSUE THREAD

**Issue by MishaStrittmatter** [kit-sdq/MRS-Editor#28]
The title says it all. Applies to optional and mandatory single relations.

**Comment by aminekechaou** [comment]
It seems to work fine for me. Can you provide more info?

**Comment by MishaStrittmatter** [comment]
I'm afraid no. It never works for me. E.g., create two new subfeatures (that are completely unrelated). I cannot create a child relation between them.

**Comment by MishaStrittmatter** [comment]
But it also does not work in every other constellation I tried.

**Comment by MishaStrittmatter** [comment]
Maybe it is caused by my buggy eclipse. => Closed for now
